enum StringsEnum {
  splashTitle('Manage your Day with '),
  demoEmail('demo@mindmate.com'),
  mindmate('MindMate'),
  startText('Let’s Start'),
  welcomeBack('Welcome Back!'),
  emailAddress('Email Address'),
  password('Password'),
  forgotPassword('Forgot Password?'),
  orContinueWith('Or continue with'),
  google('Google'),
  logIn('Log In'),
  startChat('Start a new chat'),
  progress('progress'),
  history('history'),
  profile('profile'),
  notifications('notifications'),
  dontHaveAnAccount('Don’t have an account?'),
  signUp('Sign Up'),
  createYourAccount('Create your account'),
  fullName('Full Name'),
  alreadyHaveAnAccount('Already have an account?'),
  privacyPolicy(
    'I have read & agreed to Mindmate Privacy Policy,Terms & Condition',
  ),
  messages('Messages'),
  privacyPolicyFirstPart('I have read & agreed to Mindmate'),
  privacyPolicySecondPart('Privacy Policy,Terms & Condition'),
  logout('Logout'),
  howAreYouFeelingToday('Bugün nasıl hissediyorsun?'),
  todaysChatsRemaining('Kalan günlük sohbet hakkı'),
  shareYourFeelings('Duygularını paylaş'),
  noChatsYet('Henüz hiç sohbet başlatmadın'),
  startYourFirstChat('İlk sohbetini başlat ve duygularını paylaş'),
  todaysConversations('Bugünün Sohbetleri'),
  dailyLimitReached('Günlük limit doldu'),
  comeBackTomorrow('Yarın tekrar gel ve duygularını paylaş'),
  morning('Morning'),
  afternoon('Afternoon'),
  evening('Evening'),
  aiResponse('AI Yanıtı'),
  writeYourFeelingsHere('Duygularını buraya yaz...'),
  send('Send'),
  aiIsThinking('AI düşünüyor...'),
  chatCompleted('Sohbet tamamlandı'),
  thankYouForSharing('Paylaşımın için teşekkürler!'),
  historyTitle('Geçmiş'),
  today('Bugün'),
  yesterday('Dün'),
  noHistoryYet('Henüz geçmiş yok'),
  startChattingToSeeHistory('Sohbet etmeye başla ve geçmişini gör'),
  chats('sohbet');

  final String value;
  const StringsEnum(this.value);
}
