enum StringsEnum {
  splashTitle('Manage your Day with '),
  demoEmail('demo@mindmate.com'),
  mindmate('MindMate'),
  startText('Let’s Start'),
  welcomeBack('Welcome Back!'),
  emailAddress('Email Address'),
  password('Password'),
  forgotPassword('Forgot Password?'),
  orContinueWith('Or continue with'),
  google('Google'),
  demoName('Fazil Laghari'),
  logIn('Log In'),
  startChat('Start a new chat'),
  progress('progress'),
  history('history'),
  profile('profile'),
  notifications('notifications'),
  dontHaveAnAccount('Don’t have an account?'),
  signUp('Sign Up'),
  createYourAccount('Create your account'),
  fullName('Full Name'),
  alreadyHaveAnAccount('Already have an account?'),
  privacyPolicy(
    'I have read & agreed to Mindmate Privacy Policy,Terms & Condition',
  ),
  messages('Messages'),
  privacyPolicyFirstPart('I have read & agreed to Mindmate'),
  privacyPolicySecondPart('Privacy Policy,Terms & Condition'),
  logout('Logout'),
  howAreYouFeelingToday('How are you feeling today?'),
  todaysChatsRemaining('Daily chats remaining'),
  shareYourFeelings('Share your feelings'),
  noChatsYet('No chats yet'),
  startYourFirstChat('Start your first chat and share your feelings'),
  todaysConversations('Today\'s Conversations'),
  dailyLimitReached('Daily limit reached'),
  comeBackTomorrow('Come back tomorrow to share your feelings'),
  morning('Morning'),
  afternoon('Afternoon'),
  evening('Evening'),
  aiResponse('AI Response'),
  writeYourFeelingsHere('Write your feelings here...'),
  send('Send'),
  aiIsThinking('AI is thinking...'),
  chatCompleted('Chat completed'),
  thankYouForSharing('Thank you for sharing!'),
  historyTitle('History'),
  today('Today'),
  yesterday('Yesterday'),
  noHistoryYet('No history yet'),
  startChattingToSeeHistory('Start chatting to see your history'),
  chats('chats'),
  myTasks('My Tasks'),
  privacy('Privacy'),
  setting('Setting');

  final String value;
  const StringsEnum(this.value);
}
